# Generated by Django 4.2.1 on 2023-10-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_alter_menclothing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menclothing',
            name='category',
            field=models.CharField(choices=[('T-SHIRT', 'T-Shirt'), ('SHIRT', 'Shirt'), ('JEANS', 'Jeans'), ('JACKET', 'Jacket'), ('COAT', 'Coat')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
