# Generated by Django 4.2.6 on 2023-10-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_menclothing_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='menclothing',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
