# Generated by Django 4.2.6 on 2023-11-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='menclothing',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
